model_config:
  lags: 512
  embedding_dim: 768
  n_blocks: 12
  pool_size: 4
  number_of_heads: 4
  number_ts: 264
  number_of_clusters: None
  ## As long as really want to experiment, do not touch any part of below ## s
  # Upsampling_Details #
  conv_activation: F.gelu
  conv_FFN_activation: F.gelu
  channel_shuffle_group: 2
  conv_dense_bias: True
  conv_FFN_bias: True
  dropout_FFN: 0.2
  dropout_linear: 0.2
  # Attention_Block_Details #
  FFN_dropout: 0.2
  FFN_activation: F.gelu
  FFN_expansion_size: 4
  att_head_dropout: 0.2
      
trainer_config:
  save_every: 1
  max_epochs: 5
  snapshot_name: "small_model"
  snapshot_dir: "/model"
  compile_model: True
  use_wnb: False

  
optimizer_config:
  lr: 0.000001
  weight_decay: 0.00001
  momentum: 0.99

scheduler_config:
  T_max: 15

data:
  train_path:
   file: "data/array_train.dat"
   length_file: "data/lengthsarray_train.dat"
   file_names: "data/names_array_train.txt"
   lags: 512 # 512 -> 1 prediction, we will do
  val_path:
   file: "data/array_test.dat"
   length_file: "data/lengthsarray_test.dat"
   file_names: "data/names_array_test.txt"
   lags: 512 # 512 -> 1 prediction, we will do

  
  train_data_details:
   batch_size: 256
   num_workers: 4
 #  shuffle: True
   pin_memory: True
   persistent_workers: True
   prefetch_factor: 2

  val_data_details:
   batch_size: 256
   num_workers: 4
#   shuffle: False
   pin_memory: True
   drop_last: True
   

